###
POST https://us-central1-shiper-ac3d7.cloudfunctions.net/tracker
Content-Type: application/json

{
    "code":"EZ3000000003",
    "carrier": "USPS"
}

###
GET http://localhost:5001/shiper-ac3d7/us-central1/sendPushNotification

###
GET http://localhost:5001/shiper-ac3d7/us-central1/testData